var group___tau_labs_modules =
[
    [ "Actuator Module", "group___actuator_module.html", "group___actuator_module" ],
    [ "Airspeed Module", "group___airspeed_module.html", "group___airspeed_module" ],
    [ "Altitude hold module", "group___altitude_hold_module.html", "group___altitude_hold_module" ],
    [ "Copter Control Attitude Estimation", "group___attitude_module_c_c.html", "group___attitude_module_c_c" ],
    [ "Attitude and state estimation module", "group___attitude_module.html", "group___attitude_module" ],
    [ "Autotuning Module", "group___autotuning_module.html", "group___autotuning_module" ],
    [ "Battery Module", "group___battery_module.html", "group___battery_module" ],
    [ "Camera Stabilization Module", "group___camera_stab.html", "group___camera_stab" ],
    [ "Com Port to USB VCP Bridge Module", "group___com_usb_bridge_module.html", "group___com_usb_bridge_module" ],
    [ "Fault Module", "group___fault_module.html", "group___fault_module" ],
    [ "Read the firmware IAP values", "group___firmware_i_a_p_module.html", "group___firmware_i_a_p_module" ],
    [ "Fixed wing path follower module", "group___fixed_wing_path_follower.html", "group___fixed_wing_path_follower" ],
    [ "Flight Plan Module", "group___flight_plan.html", "group___flight_plan" ],
    [ "Generic I2C sensor interface", "group___generic_i2_c_sensor.html", "group___generic_i2_c_sensor" ],
    [ "GPS Module", "group___g_s_p_module.html", "group___g_s_p_module" ],
    [ "Path follower for ground based vehicles", "group___ground_path_follower.html", "group___ground_path_follower" ],
    [ "Control Module", "group___control.html", "group___control" ],
    [ "osdgen Module", "group___o_s_d_g_e_n_module.html", "group___o_s_d_g_e_n_module" ],
    [ "osdinput Module", "group__osdinput_module.html", "group__osdinput_module" ],
    [ "WavPlayer Module", "group___wav_player_module.html", "group___wav_player_module" ],
    [ "OveroSync Module", "group___overo_sync_module.html", "group___overo_sync_module" ],
    [ "Path Follower Module", "group___path_follower_module.html", "group___path_follower_module" ],
    [ "Path Planner Module", "group___path_planner_module.html", "group___path_planner_module" ],
    [ "PipXtreme Module", "group___pip_xtreme_module.html", "group___pip_xtreme_module" ],
    [ "Com Port to Radio Bridge Module", "group___radio_com_bridge_module.html", "group___radio_com_bridge_module" ],
    [ "Sensor acquisition module", "group___sensors.html", "group___sensors" ],
    [ "Visualization module for simulation", "group___visualization_module.html", "group___visualization_module" ],
    [ "Stabilization Module", "group___stabilization_module.html", "group___stabilization_module" ],
    [ "Copter Control State Estimation", "group___c_c_state.html", "group___c_c_state" ],
    [ "System Module", "group___system_module.html", "group___system_module" ],
    [ "Telemetry Module", "group___telemetry_module.html", "group___telemetry_module" ],
    [ "TxPID Module", "group___tx_p_i_d_module.html", "group___tx_p_i_d_module" ],
    [ "UAVO to Mavlink Bridge Module", "group___u_a_v_o_mavlink_bridge.html", "group___u_a_v_o_mavlink_bridge" ],
    [ "Vibration analysis module", "group___vibration_analysis_module.html", "group___vibration_analysis_module" ],
    [ "VTOL path follower module", "group___vtol_path_follower.html", "group___vtol_path_follower" ]
];